#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x86

configuration: Debug

build:
  parallel: true                  # enable MSBuild parallel builds
  project: HM3CoreKill/HM3CoreKill.sln     # path to Visual Studio solution or project

  #---------------------------------#
  #      artifacts configuration    #
  #---------------------------------#

  artifacts:
    # pushing a single file with environment variable in path and "Deployment name" specified
    - path: HM3CoreKill\Debug\Launcher.exe
      name: Launcher

    - path: HM3CoreKill\Debug\HM3CoreKill.dll
      name: HM3CoreKill

# Discord WebHook
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL