#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x86

configuration: Debug

build:
  parallel: true                  # enable MSBuild parallel builds
  project: HM3CoreKill/HM3CoreKill.sln     # path to Visual Studio solution or project

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build: 7z a ReHitman.zip HM3CoreKill\Debug\Launcher.exe HM3CoreKill\Debug\HM3CoreKill.dll

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  - path: ReHitman.zip
    name: ReHitman

#---------------------------------#
#         Discord WebHook         #
#---------------------------------#

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL